= AutoSuggest elements

An `AutoSuggestFormElement` writes a `<div>` tag to the output containing all markup for an autoSuggest control.

== Element and builder

The `AutoSuggestFormElement` has an equivalent `AutoSuggestFormElementBuilder`.
A builder can be created using `BootstrapUiBuilders.autosuggest()` factory methods.

The `AutoSuggestFormElementBuilder` supports configuring templates by specifying a `ViewElementBuilder` for the given template.
Depending on the template, different objects are available within the context of the template.
These can be specified with curly braces, for example `{\{query}}`, within the template and will be interpolated when the element is rendered.
The following templates are available:

[options=header,cols="1,3"]
|===

| Template name
| Description

| header
| Rendered at the top of the dataset when suggestions are present.
In the rendering context, the `query` and the `suggestions` will be available.

| footer
| Rendered at the top of the dataset when suggestions are present.
In the rendering context, the `query` and the `suggestions` will be available.

| pending
| Rendered when there are no synchronous suggestions available, but asynchronous suggestions are being fetched.
In the rendering context the `query` will be available.

| suggestion
| Used to render a single suggestion.
The associated suggestion object will be available in the context.
If no template is configured, the default template `<div>{\{value}}</div>` will be used.

| notFound
| Rendered when no suggestions could be found for the current query.
In the rendering context the `query` will be available.

|===

When configuring a template, optionally a dataset id can be specified for which the template should be added.

.Configuring a template for a specific dataset
[source,java,indent=0]
----
BootstrapUiBuilders
    .autosuggest()
    .notFoundTemplate( "people" ,BootstrapUiBuilders.text("No results found") ) # <1>
    .build()
----
<1> Configure a `notFound` template for the dataset with id `people`.
If the id is not specified, the template would be applied for the default dataset.

== AutoSuggestFormElementConfiguration
The autoSuggest control takes in a `AutoSuggestFormElementConfiguration` to configure the dataSet options

[options=header,cols="1,1"]
|===

| Method
| Description

| `withDataSet`
| Configure the dataset with the given name, if it is not yet present, it will be added first.

| `setEndpoint`
| Sets the remote url endpoint where to fetch suggestions.

| `showHint`
| Should the textbox show a hint for auto-completion.

| `highlight`
| Highlight the matching input text in the suggestions.

| `minLength`
| Minimum length the input value should have before fetching suggestion.

|===

[#dynamic-configuration-dataset]
== Dynamic configuration of a dataset

An autosuggest form element supports clientside modification of the active dataset(s).
On the autosuggest element itself an attribute `datasets` is available which holds the configured https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md[Bloodhound] search engines.
By accessing the datasets, the urls used to fetch the data can be modified:

[source,javascript,indent=0]
----
$( '[data-bootstrapui-adapter-type="autosuggest"]' ) # <1>
    .data( 'datasets' )['default'].remote.url = '/active-users'; # <2>
----
<1> Select the autosuggest for which you want to modify a dataset.
In this case, we're selecting an autosuggest form element by its corresponding xref:control-adapters/autosuggest-adapter.adoc[control adapter].
<2> Find the dataset by name and reconfigure the remote url.
Now the new url will be used when data is fetched.

== Examples

=== Creating an autoSuggest element

Given the following builder configuration:

[source,java,indent=0]
----
BootstrapUiBuilders
    .autosuggest()
    .configuration(
            AutoSuggestFormElementConfiguration.withDataSet(
                    dataSet -> dataSet.remoteUrl( "/bootstrapAutosuggest/suggest?query={{query}}" )
            )
    ).build()
----

The following markup would be rendered:

[source,html,indent=0]
----
<div class="axbum-typeahead" data-bootstrapui-autosuggest="{&quot;highlight&quot;:true,&quot;hint&quot;:true,&quot;minLength&quot;:1,&quot;_datasets&quot;:[{&quot;name&quot;:&quot;default&quot;,&quot;bloodhound&quot;:{&quot;remote&quot;:{&quot;url&quot;:&quot;/bootstrapAutosuggest/suggest?query={{query}}&quot;}}}]}">
   <span class="twitter-typeahead" style="position: relative; display: inline-block;">
      <input autocomplete="off" type="search" class="js-typeahead form-control tt-hint" readonly="" spellcheck="false" tabindex="-1" dir="ltr" style="position: absolute; top: 0px; left: 0px; border-color: transparent; box-shadow: none; opacity: 1; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(255, 255, 255);"><input autocomplete="off" type="search" class="js-typeahead form-control tt-input" spellcheck="false" dir="auto" style="position: relative; vertical-align: top; background-color: transparent;">
      <pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre>
      <div class="tt-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;">
         <div class="tt-dataset tt-dataset-default"></div>
      </div>
   </span>
   <input type="hidden" class="js-typeahead-value">
</div>
----

=== Configuring a template

The following builder configuration adds a `notFound` template:

[source,java,indent=0]
----
BootstrapUiBuilders
    .autosuggest()
    .configuration(
            AutoSuggestFormElementConfiguration.withDataSet(
                    dataSet -> dataSet.remoteUrl( "/bootstrapAutosuggest/suggest?query={{query}}" )
            )
    )
    .notFoundTemplate( BootstrapUiBuilders.div().css( "autosuggest-not-found" )
                                          .add( BootstrapUiBuilders.text( "There are no results available for '{{query}}'" ) ) ) # <1>
    .build()
----

Given the query 'John', the following markup would be rendered in the suggestions dropdown if there are no results:

[source,html,indent=0]
----
<div class="autosuggest-not-found">There are no results available for 'John'</div>
----