= Fieldset elements

A `FieldsetFormElement` writes a `<fieldset>` tag to the output.

== Element and builder

The `ViewElement` implementation for a fieldset element is a `FieldsetFormElement` and has a corresponding `FieldsetFormElementBuilder`.
A `FieldsetFormElement` can also be created via the `BootstrapViewElements.bootstrap.builders#fieldset` factory methods.

== Examples

=== Creating a fieldset

[source,java,indent=0]
----
import static com.foreach.across.modules.bootstrapui.ui.factories.BootstrapViewElements.bootstrap;

bootstrap.builders.fieldset().legend("Author")
                   .build();
----

=== Child elements

[source,java,indent=0]
----
import static com.foreach.across.modules.bootstrapui.ui.factories.BootstrapViewElements.bootstrap;

bootstrap.builders.fieldset().legend( "Author" )
                   .add( bootstrap.builders.textbox() )
                   .build()
----

=== Customizing the legend

The legend can also have additional child view elements, which can be added through the `Legend` builder of the fieldset.


[source,java,indent=0]
----
import static com.foreach.across.modules.bootstrapui.ui.factories.BootstrapViewElements.bootstrap;

bootstrap.builders.fieldset()
       .legend() # <1>
       .text( "Author" )
       .add( IconSet.iconSet( FONT_AWESOME_SOLID_ICON_SET ).icon( "user" ) )
       .and()
       .build()
----

[WARNING]
====
Providing a value to the `legend` method will not give access to the builder for the legend element.
As such, the following configuration will add the provided view elements to the fieldset instead of to the legend.

[source,java,indent=0]
----
import static com.foreach.across.modules.bootstrapui.ui.factories.BootstrapViewElements.bootstrap;

bootstrap.builders.fieldset()
   .legend( "Author" )
   .add( IconSet.iconSet( FONT_AWESOME_SOLID_ICON_SET ).icon( "user" )  )
   .build()
----
====

