= Textbox/Textarea elements

A `TextboxFormElement` writes either an `<input>` or a `textarea` tag to the output.
It is also a base control element that is reused for several other controls, such as xref::components/form-controls/numeric.adoc[numeric controls] and xref::components/form-controls/datetime.adoc[date controls].

== Element and builder

The `ViewElement` implementation is `TextboxFormElement`, which also has a specialized version `TextareaFormElement`.
Both of these elements can be configured via a `TextboxViewElementBuilder`.
A builder can also be created by using the `BootstrapUiBuilders#textbox` or `BootstrapUiBuilders#textarea` factory methods.

== Configurable settings

A `TextboxFormElement` can easily be customized through a variety of settings.

[opts="header",cols="1,2"]
|===

| Setting
| Description

| type
| The type of a `TextBoxFormElement` influences the datatype for which the control is rendered.
This can be used to for example render a control for a password field instead of a text field.

The default type is `TextBoxFormElement.Type.TEXT`

| placeholder
| Sets a placeholder that is rendered if no data is present.

| text
| The value that the element holds.

| maxLength
| The maximum amount of characters that can be entered in the field.

| disableLineBreaks
| Whether line breaks are allowed within the textbox or not.

|===

A `TextAreaElement` is a specialized `TextBoxFormElement` and contains some additional properties.

[opts="header",cols="1,2,1"]
|===

| Setting
| Description
| Default value

| rows
| The initial rows that should be available in the textarea
| 3

| autoSize
| Whether the textarea should grow and shrink with content that is added.
| true

|===

== Examples

=== Creating a textbox

Given the following builder configuration:

[source,java,indent=0]
----
BootstrapUiBuilders.textbox()
                   .build();
----

The following markup would be rendered:

[source,html,indent=0]
----
<input type="text" class="form-control">
----

=== Multiline & Autosizing

Given the following builder configuration:

[source,java,indent=0]
----
BootstrapUiBuilders.textbox()
                   .autoSize()
                   .multiLine( 3 )
                   .build();

// Equivalent configuration as the above
BootstrapUiBuilders.textarea()
                   .build();

----

The following markup would be rendered:

[source,html,indent=0]
----
<textarea rows="3" class="form-control js-autosize" style="overflow: hidden; overflow-wrap: break-word; resize: horizontal; height: 74px;"></textarea>
----

As seen in the markup, additional classes such as js-autosize are provided to support the autosizing.
Depending on the configuration, additional markup and web resources are added to support settings.