= 1.x.x release notes

[#1-2-0]
== 1.2.0.RELEASE
* added `BootstrapUiBuilders` class that is a static facade for all builders
** `BootstrapUiFactory` and `BootstrapUiComponentFactory` beans are still available, but because both of them operate stateless, the facade was added to reduce wiring verbosity
* textbox improvements:
** `TextboxFormElement` has a property *disableLineBreaks* that will disable the ENTER key
** the `TextboxFormElementBuilder` will generate a valid single-line auto-sizing textarea if auto-size is requested on a normal textbox

== 1.1.0.RELEASE
* added several <<NavComponentBuilder,builders for rendering menu structures>>: `DefaultNavComponentBuilder`, `BreadcrumbNavComponentBuilder` and `PanelsNavComponentBuilder`
** all nav related builders now also support message code snippets in `Menu` titles: putting for example _#{my.code=Item title}_ as value will be replaced by the Locale specific message for _my.code_ or by _Item title_ if the message code can't be resolved
* added support for <<bootstrap-select,bootstrap-select dropdown lists>> on `OptionsFormElementBuilder` and `SelectFormElement`
** allows for more advanced and user-friendly dropdown controls
* the BootstrapUiModule <<bootstrapui-javascript,javascript library supports adding initializer extensions>>

== 1.0.0.RELEASE
Initial public release available on http://search.maven.org/[Maven central].