= 3.x.x release notes

[#3-0-0]
== 3.0.0-SNAPSHOT

*Requires Across 5.0.0*

=== Library upgrades

* updated versions for external libraries and upgraded to their Bootstrap 4 variants
** updated autoNumeric from `1.9.30` to `4.5.4`
*** registered the corresponding AutoNumeric object as a `data-autoNumeric` attribute
** updated MomentJS from `2.10.6` to `2.24.0`
** migrated from `Eonasdan DateTimePicker 4.14.30` to `Tempus Dominus DateTimePicker 5.1.2`
*** DateTimePickers always require a unique controlName to ensure it works correctly.
** updated autoSize from `3.0.20` to `4.0.2`
** updated bootstrap select from `1.12.2` to `1.13.10`
** updated jQuery from `1.11.3` to `3.4.1`

=== Bootstrap 4 upgrades

* migrated from bootstrap 3 to https://getbootstrap.com/docs/4.3/getting-started/introduction/[Bootstrap 4] resulting in various breaking changes
* added support for Bootstrap 4 Switches, these can be found as xref:...[`ToggleFormElements`]
* reduced custom css in favor of Bootstrap 4 utility classes
* panels have been removed and migrated to cards
* iconOnly menu items are hidden using sr-only

=== Improvements & New Features

* removed `BootstrapUiBuilders` in favor of `BootstrapViewElements`.
`BootstrapViewElements` provides a static variable `bootstrap` through which `ViewElements` can be created, with a corresponding `bootstrap.builders` to easily create `ViewElementBuilders`.
* removed various attributes in favor of `WitherSetter`s to support both extendability and easy customization of @ViewElements`
* added an IconSetRegistry in which xref:[IconSets] can be registered
** IconSets can be used to maintain a set of icons throughout modules
** registered icons within an IconSet can be overridden for ease of customization
** default IconSets are registered for https://fontawesome.com/[FontAwesome 5] Regular, Solid and Brands styles
* added `checkbox-list`, `toggle-list` and `radio-list` as CSS class to the wrapping div in case of `OptionsFormElementBuilders` for ease of customization